# Generated by Django 5.2.17 on 2026-08-25 00:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import portal.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('last_used_step', models.BigIntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=30)),
                ('actor_reference_hash', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='portal_audi_object__53a82b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=portal.models.new_reference, editable=False, max_length=24, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('more_info', 'More information required'), ('approved', 'Approved'), ('declined', 'Declined'), ('contract_sent', 'Contract sent'), ('signed', 'Signed'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('applicant_note', models.TextField(blank=True, max_length=1000)),
                ('terms_version', models.CharField(max_length=60)),
                ('privacy_version', models.CharField(max_length=60)),
                ('terms_accepted_at', models.DateTimeField()),
                ('privacy_accepted_at', models.DateTimeField()),
                ('submitted_ip_hash', models.CharField(max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('is_demo', models.BooleanField(default=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='portal_loan_status_51d8c6_idx'), models.Index(fields=['email'], name='portal_loan_email_4d482b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for signature'), ('signed', 'Signed'), ('void', 'Void')], default='draft', max_length=16)),
                ('template_version', models.CharField(max_length=80)),
                ('agreement_text_snapshot', models.TextField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('apr_percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('27.00'))])),
                ('term_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('first_payment_date', models.DateField()),
                ('daily_late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('installment_schedule', models.JSONField(default=list)),
                ('lender_signatory_name', models.CharField(max_length=160)),
                ('lender_accepted_at', models.DateTimeField()),
                ('draft_pdf', models.FileField(blank=True, upload_to=portal.models.private_upload_path)),
                ('final_pdf', models.FileField(blank=True, upload_to=portal.models.private_upload_path)),
                ('draft_document_hash', models.CharField(blank=True, max_length=64)),
                ('final_document_hash', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='portal.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.FileField(upload_to=portal.models.private_upload_path)),
                ('signer_typed_name', models.CharField(max_length=160)),
                ('signer_email', models.EmailField(max_length=254)),
                ('agreed_at', models.DateTimeField()),
                ('document_hash_at_signing', models.CharField(max_length=64)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent_hash', models.CharField(max_length=64)),
                ('consent_text_version', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signature_evidence', to='portal.contract')),
            ],
        ),
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='portal.contract')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('reviewer', 'Reviewer')], default='reviewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'action'), name='unique_throttle_bucket')],
            },
        ),
    ]
